exports.config = {
	appName: 'Rocket League Map Manager',
	renderer_path: './src/renderer/',
	public_path: './src/renderer/public/',
	preload_path: './',
	save_path: './',
	map_folder: './TAGame/CookedPCConsole/',
	default_map: 'Labs_CirclePillars_P.upk',
	send_channels: [
		'get-path',
		'edit-folder',
		'edit-import',
		'get-list',
		'add-map',
		'handle-selected',
		'remove',
		'switch-active',
	],
	receive_channels: ['ready', 'app-path', 'game-path', 'to-open', 'list', 'selected', 'active'],
};
